import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the focused MIDI track player", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");

  assert.match(layout, /MIDI Track Player/);
  assert.match(page, /new Midi/);
  assert.match(page, /arrayBuffer/);
  assert.match(page, /muted/);
  assert.match(page, /solo/);
  assert.match(page, /controlChanges\[64\]/);
  assert.match(page, /keySignatures/);
  assert.match(page, /header\.tempos/);
  assert.match(page, /toArray/);
  assert.match(page, /deleteTrack/);
  assert.match(page, /presetFor/);
  assert.match(page, /repairMidiText/);
  assert.match(page, /TextDecoder\(encoding/);
  assert.match(page, /utf8ByteString/);
  assert.match(page, /displayName/);
  assert.match(page, /Kalimba · Grand Piano map/);
  assert.match(page, /ratio: 2\.76/);
  assert.match(page, /decayScale: 0\.48/);
  assert.match(page, /instrument\.number === 46/);
  assert.match(page, /ratio: 4\.03/);
  assert.match(page, /transposeKalimba: true/);
  assert.match(page, /Kalimba · Orchestral Harp map/);
  assert.match(page, /className="global-playhead"/);
  assert.match(page, /TIMBRE_STORAGE_KEY/);
  assert.match(page, /window\.localStorage\.setItem/);
  assert.match(page, /试听当前设置/);
  assert.match(page, /saveTimbre/);
  assert.match(page, /fetchInstruments/);
  assert.match(page, /favoriteTimbres/);
  assert.match(page, /track-timbre-select/);
  assert.match(page, /laneGeometry\.left/);
  assert.match(page, /mode: "sustained"/);
  assert.match(page, /noteOff \+ preset\.release/);
  assert.match(page, /setTargetAtTime\(0\.0001/);
  assert.match(page, /compressor\.threshold\.value = -22/);
  assert.match(page, /播放/);
  assert.match(page, /暂停/);
  assert.match(css, /\.track-row/);
  assert.match(css, /\.transport-card \{ position: sticky/);
  assert.match(css, /\.global-playhead/);
  assert.match(css, /\.timbre-panel/);
  assert.match(css, /\.scrubber \{ position: absolute/);
  assert.match(css, /\.main-play/);
  assert.match(css, /\.edit-tools/);
  assert.doesNotMatch(page, /splitRegion|mergeRegions/);
});

test("ships the PHP and MySQL timbre manager", async () => {
  const manager = await readFile(new URL("../app/timbres/page.tsx", import.meta.url), "utf8");
  const api = await readFile(new URL("../php-server/api/instruments.php", import.meta.url), "utf8");
  const bootstrap = await readFile(new URL("../php-server/api/bootstrap.php", import.meta.url), "utf8");
  const schema = await readFile(new URL("../php-server/database.sql", import.meta.url), "utf8");
  const packageJson = await readFile(new URL("../package.json", import.meta.url), "utf8");

  assert.match(manager, /MIDI 音色管理/);
  assert.match(manager, /试听 1 2 3 4 5 6 7 1/);
  assert.match(manager, /永久保存到 MySQL/);
  assert.match(manager, /favorite/);
  assert.match(api, /require_admin/);
  assert.match(api, /UPDATE harmonic_instrument_presets/);
  assert.match(bootstrap, /GM_NAMES/);
  assert.match(bootstrap, /hash_equals/);
  assert.match(bootstrap, /shared\/database\.php/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS harmonic_instrument_presets/);
  assert.match(packageJson, /build:php/);
});
