import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the focused MIDI track player", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");

  assert.match(layout, /MIDI Track Player/);
  assert.match(page, /new Midi/);
  assert.match(page, /arrayBuffer/);
  assert.match(page, /muted/);
  assert.match(page, /solo/);
  assert.match(page, /controlChanges\[64\]/);
  assert.match(page, /buildSustainRanges/);
  assert.match(page, /sustainRangesFromEvents/);
  assert.match(page, /trimmedPedalRanges/);
  assert.match(page, /pedalDown/);
  assert.match(page, /pedalUp/);
  assert.match(page, /className="sustain-range"/);
  assert.match(page, /段踏板/);
  assert.match(page, /keySignatures/);
  assert.match(page, /header\.tempos/);
  assert.match(page, /toArray/);
  assert.match(page, /deleteTrack/);
  assert.match(page, /presetFor/);
  assert.match(page, /repairMidiText/);
  assert.match(page, /TextDecoder\(encoding/);
  assert.match(page, /utf8ByteString/);
  assert.match(page, /displayName/);
  assert.match(page, /fetchCustomTimbres/);
  assert.match(page, /fetchMappings/);
  assert.match(page, /ratio: 2\.76/);
  assert.match(page, /decayScale: 0\.48/);
  assert.match(page, /program === 46/);
  assert.match(page, /ratio: 4\.03/);
  assert.match(page, /customTimbre\.transposeKalimba/);
  assert.match(page, /effectiveCustom/);
  assert.match(page, /colorForTimbre/);
  assert.match(page, /background: timbreColor/);
  assert.doesNotMatch(page, /TRACK_COLORS/);
  assert.match(page, /className="global-playhead"/);
  assert.match(page, /trimGuideTick/);
  assert.match(page, /trimGuideSeconds/);
  assert.match(page, /region-trim-guide/);
  assert.match(page, /TRIM OUT/);
  assert.match(page, /TRIM IN/);
  assert.match(page, /fetchInstruments/);
  assert.match(page, /favoriteTimbres/);
  assert.match(page, /timbre-picker/);
  assert.match(page, /P\{String\(effectiveProgram \+ 1\)/);
  assert.match(page, /event\.ticks > 0/);
  assert.match(page, /laneGeometry\.left/);
  assert.match(page, /mode: "sustained"/);
  assert.match(page, /noteOff \+ preset\.release/);
  assert.match(page, /setTargetAtTime\(0\.0001/);
  assert.match(page, /compressor\.threshold\.value = -22/);
  assert.match(page, /classifyTrackForPractice/);
  assert.match(page, /fitToPianoRange/);
  assert.match(page, /mergePracticeTracks/);
  assert.match(page, /生成钢琴练习版/);
  assert.match(page, /Piano Practice/);
  assert.match(page, /excludedFromExport/);
  assert.match(page, /36–96/);
  assert.match(page, /selectedTracks = project\.tracks\.filter\(\(track\) => track\.solo\)/);
  assert.match(page, /请先点亮至少一条轨道的 S/);
  assert.match(page, /另存 S 轨/);
  assert.match(page, /选择导出/);
  assert.match(page, /timelineValueChanges/);
  assert.match(page, /encodeMidiWithValidKeySignatures/);
  assert.match(page, /parseMidi/);
  assert.match(page, /keyIndex - 7/);
  assert.match(page, /tempoChangeEvents/);
  assert.match(page, /keyChangeEvents/);
  assert.match(page, /activeTimeSignature/);
  assert.match(page, /buildRulerMarks/);
  assert.match(page, /timeSignatures/);
  assert.match(page, /\{activeMeter\[0\]\}\/\{activeMeter\[1\]\}/);
  assert.match(page, /16分格/);
  assert.match(page, /timelineZoom/);
  assert.match(page, /initialSegments/);
  assert.match(page, /beginRegionGesture/);
  assert.match(page, /moveRegionGesture/);
  assert.match(page, /gestureAnchorTick = regionGesture\.mode === "trim-end"/);
  assert.match(page, /targetTick - gestureAnchorTick/);
  assert.match(page, /preciseDeltaTicks = Math\.round\(rawDelta\)/);
  assert.match(page, /moveDeltaTicks = Math\.round\(rawDelta \/ snapTicks\) \* snapTicks/);
  assert.match(page, /originalEndTick - 1/);
  assert.match(page, /finishRegionGesture/);
  assert.match(page, /region-handle start/);
  assert.match(page, /region-handle end/);
  assert.match(page, /Region 已平移/);
  assert.match(page, /Region 已 Trim/);
  assert.match(page, /eventRegionIds/);
  assert.match(page, /belongsToRegion/);
  assert.match(page, /deleteRegion/);
  assert.match(page, /Region 已删除/);
  assert.match(page, /Region 已移到/);
  assert.match(page, /regionsOverlap/);
  assert.match(page, /closestAvailableRegionStart/);
  assert.match(page, /目标位置已有 Region，不能重叠/);
  assert.match(page, /splitRegionAtPlayhead/);
  assert.match(page, /splitRegionSequence/);
  assert.match(page, /event\.shiftKey && event\.code === "KeyT"/);
  assert.doesNotMatch(page, /\(event\.metaKey \|\| event\.ctrlKey\) && event\.key\.toLowerCase\(\) === "t"/);
  assert.match(page, /className="region-split"/);
  assert.match(page, /从播放线分割 Region（Shift\+T）/);
  assert.match(page, /请先把播放线放在选中 Region 内部/);
  assert.match(page, /className=\{`region-drop-preview/);
  assert.match(page, /移动到这里/);
  assert.match(page, /captureEditorSnapshot/);
  assert.match(page, /restoreEditorSnapshot/);
  assert.match(page, /undoHistoryRef/);
  assert.match(page, /redoHistoryRef/);
  assert.match(page, /HISTORY_LIMIT = 30/);
  assert.match(page, /event\.code === "KeyZ"/);
  assert.match(page, /event\.code === "KeyY"/);
  assert.match(page, /!event\.shiftKey \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey/);
  assert.match(page, /SHIFT Z/);
  assert.match(page, /SHIFT Y/);
  assert.doesNotMatch(page, /CTRL\/⌘ Z|CTRL Y/);
  assert.match(page, /data-track-id/);
  assert.match(page, /Delete \/ Backspace/);
  assert.match(page, /thinRulerMarks/);
  assert.match(page, /addEventListener\("wheel", onWheel, \{ passive: false \}\)/);
  assert.match(page, /addEventListener\("gesturestart", onSafariGestureStart, \{ passive: false \}\)/);
  assert.match(page, /addEventListener\("gesturechange", onSafariGestureChange, \{ passive: false \}\)/);
  assert.match(page, /addEventListener\("gestureend", onSafariGestureEnd, \{ passive: false \}\)/);
  assert.match(page, /safariPinch\.startZoom \* scale/);
  assert.match(page, /horizontalDelta/);
  assert.match(page, /event\.deltaX/);
  assert.match(page, /timelineScrollbarRef/);
  assert.match(page, /handleTimelineScrollbar/);
  assert.match(page, /轨道区捏合伸缩/);
  assert.doesNotMatch(page, /Zoom In|Zoom Out|横向查看位置/);
  assert.doesNotMatch(page, /REGION EDITOR|裁剪左侧|裁剪右侧|删除片段|开始位置（16分格）/);
  assert.doesNotMatch(page, /splitSelectedSegment|trimSelectedSegment|deleteSelectedSegment|moveSelectedSegment|rebuildTrackFromSegments/);
  assert.match(page, /播放/);
  assert.match(page, /暂停/);
  assert.match(css, /\.track-row/);
  assert.doesNotMatch(page, /className="transport-card"/);
  assert.doesNotMatch(page, /aria-label="播放进度"/);
  assert.doesNotMatch(css, /\.transport-card|\.main-play|\.scrubber/);
  assert.match(page, /className="project-live-status"/);
  assert.match(page, /APP_VERSION = "2026\.07\.30\.5"/);
  assert.match(page, /checkForUpdate/);
  assert.match(page, /cache: "no-store"/);
  assert.match(page, /new DOMParser\(\)/);
  assert.match(page, /data-app-version=\{APP_VERSION\}/);
  assert.match(page, /当前已是最新版本/);
  assert.match(page, /发现新版本/);
  assert.match(css, /\.version-badge/);
  assert.match(css, /\.track-row:has\(\.track-segment\.selected\)/);
  assert.match(css, /background: #e9e3ff/);
  assert.doesNotMatch(css, /box-shadow: 0 0 5px currentColor/);
  assert.match(page, /timelineViewportRef/);
  assert.match(page, /Math\.exp\(-controlledDelta \* 0\.004\)/);
  assert.match(page, /Math\.abs\(timelineViewportRef\.current\.viewStart - nextViewStart\) < 0\.002/);
  assert.match(page, /blockBrowserWheelZoom/);
  assert.match(page, /blockBrowserGestureZoom/);
  assert.match(page, /window\.addEventListener\("wheel", blockBrowserWheelZoom, \{ passive: false, capture: true \}\)/);
  assert.match(page, /document\.addEventListener\("gesturechange", blockBrowserGestureZoom, \{ passive: false, capture: true \}\)/);
  assert.match(page, /className="ruler-event tempo"/);
  assert.match(page, /className="ruler-event key"/);
  assert.match(css, /\.ruler-event/);
  assert.match(css, /\.global-playhead/);
  assert.match(css, /\.region-trim-guide/);
  assert.match(css, /\.region-trim-guide\.trim-end/);
  assert.match(css, /\.timbre-picker/);
  assert.match(css, /\.edit-tools/);
  assert.match(css, /\.practice-builder/);
  assert.match(css, /\.practice-categories/);
  assert.match(css, /\.timeline-ruler/);
  assert.match(css, /\.ruler-mark\.measure/);
  assert.match(css, /\.timeline-scrollbar/);
  assert.match(css, /\.track-segment/);
  assert.match(css, /\.track-segment\.selected/);
  assert.match(css, /\.region-handle/);
  assert.match(css, /\.region-delete/);
  assert.match(css, /\.region-split/);
  assert.match(css, /\.track-unit\.region-drop-target/);
  assert.match(css, /\.track-unit\.region-drop-invalid/);
  assert.match(css, /\.region-drop-preview/);
  assert.match(css, /\.region-drop-preview\.invalid/);
  assert.match(css, /\.timeline-ruler-shell \{ position: sticky/);
  assert.match(css, /\.sustain-range/);
  assert.doesNotMatch(css, /\.timeline-zoom|\.segment-editor/);
  assert.doesNotMatch(page, /mergeRegions/);
});

test("ships the PHP and MySQL timbre manager", async () => {
  const manager = await readFile(new URL("../app/timbres/page.tsx", import.meta.url), "utf8");
  const api = await readFile(new URL("../php-server/api/instruments.php", import.meta.url), "utf8");
  const bootstrap = await readFile(new URL("../php-server/api/bootstrap.php", import.meta.url), "utf8");
  const schema = await readFile(new URL("../php-server/database.sql", import.meta.url), "utf8");
  const packageJson = await readFile(new URL("../package.json", import.meta.url), "utf8");

  assert.match(manager, /MIDI 音色管理/);
  assert.match(manager, /试听标准 GM/);
  assert.match(manager, /永久保存到 MySQL/);
  assert.match(manager, /favorite/);
  assert.match(manager, /toggleFavorite/);
  assert.match(manager, /await updateInstrument\(next\)/);
  assert.match(manager, /解除映射/);
  assert.match(manager, /updateMapping/);
  assert.doesNotMatch(api, /require_admin/);
  assert.doesNotMatch(manager, /管理密钥/);
  assert.match(api, /UPDATE harmonic_instrument_presets/);
  assert.match(bootstrap, /GM_NAMES/);
  assert.match(bootstrap, /shared\/database\.php/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS harmonic_instrument_presets/);
  assert.match(packageJson, /build:php/);
});

test("ships the Custom timbre library and persistent GM mappings", async () => {
  const manager = await readFile(new URL("../app/custom-timbres/page.tsx", import.meta.url), "utf8");
  const customApi = await readFile(new URL("../php-server/api/custom-timbres.php", import.meta.url), "utf8");
  const mappingApi = await readFile(new URL("../php-server/api/mappings.php", import.meta.url), "utf8");
  const bootstrap = await readFile(new URL("../php-server/api/bootstrap.php", import.meta.url), "utf8");
  const schema = await readFile(new URL("../php-server/database.sql", import.meta.url), "utf8");

  assert.match(manager, /Custom 音色列表/);
  assert.match(manager, /新建 Custom 音色/);
  assert.match(manager, /复制为新音色/);
  assert.match(manager, /发声结构由系统自动保留/);
  assert.match(manager, /saveCustomTimbre/);
  assert.match(manager, /deleteCustomTimbre/);
  assert.doesNotMatch(manager, /基础 GM 音色/);
  assert.doesNotMatch(manager, /合成引擎/);
  assert.doesNotMatch(manager, /使用 Transpose Piano 高泛音模式/);
  assert.match(customApi, /harmonic_custom_timbres/);
  assert.match(mappingApi, /harmonic_program_mappings/);
  assert.match(bootstrap, /custom-mappings-v1/);
  assert.match(bootstrap, /kalimba-orchestral-harp/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS harmonic_custom_timbres/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS harmonic_program_mappings/);
});
