import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ships the focused MIDI track player", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");

  assert.match(layout, /MIDI Track Player/);
  assert.match(page, /new Midi/);
  assert.match(page, /arrayBuffer/);
  assert.match(page, /muted/);
  assert.match(page, /solo/);
  assert.match(page, /controlChanges\[64\]/);
  assert.match(page, /keySignatures/);
  assert.match(page, /header\.tempos/);
  assert.match(page, /toArray/);
  assert.match(page, /deleteTrack/);
  assert.match(page, /presetFor/);
  assert.match(page, /repairMidiText/);
  assert.match(page, /TextDecoder\(encoding/);
  assert.match(page, /utf8ByteString/);
  assert.match(page, /displayName/);
  assert.match(page, /Kalimba · Grand Piano map/);
  assert.match(page, /ratio: 2\.76/);
  assert.match(page, /decayScale: 0\.48/);
  assert.match(page, /makeHarpString/);
  assert.match(page, /instrument\.number === 46/);
  assert.match(page, /className="global-playhead"/);
  assert.match(page, /mode: "sustained"/);
  assert.match(page, /noteOff \+ preset\.release/);
  assert.match(page, /setTargetAtTime\(0\.0001/);
  assert.match(page, /compressor\.threshold\.value = -22/);
  assert.match(page, /播放/);
  assert.match(page, /暂停/);
  assert.match(css, /\.track-row/);
  assert.match(css, /\.transport-card \{ position: sticky/);
  assert.match(css, /\.global-playhead/);
  assert.match(css, /\.main-play/);
  assert.match(css, /\.edit-tools/);
  assert.doesNotMatch(page, /splitRegion|mergeRegions/);
});
